// Writes supabase/seed.sql from the synthetic bank database export (src/lib/data/personas.generated.json).
//
//   node scripts/supabase-seed.mjs
//
// Then load it: `npx supabase db reset` locally, or paste supabase/seed.sql into the SQL editor of the
// hosted project. The upsert is idempotent, so it can be run again after a new export.
import { readFile, writeFile } from "node:fs/promises";

const data = JSON.parse(await readFile(new URL("../src/lib/data/personas.generated.json", import.meta.url), "utf8"));
const quote = (s) => `'${String(s).replaceAll("'", "''")}'`;

const rows = Object.entries(data.personas).map(
  ([id, record]) => `  (${quote(id)}, ${quote(record.customerId)}, ${quote(data.asOf)}, ${quote(JSON.stringify(record))}::jsonb)`,
);

const sql = `-- Generated by scripts/supabase-seed.mjs from src/lib/data/personas.generated.json. Do not edit by hand.
-- ${data.source}, as of ${data.asOf}. 100% synthetic.

insert into public.personas (id, customer_id, as_of, record) values
${rows.join(",\n")}
on conflict (id) do update
  set customer_id = excluded.customer_id,
      as_of = excluded.as_of,
      record = excluded.record,
      updated_at = now();
`;

await writeFile(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log(`supabase/seed.sql: ${rows.length} personas, as of ${data.asOf}`);
